### ISSUE TITLE
ESC should cancel range selection

### ISSUE THREAD

**Issue by iweindesmedt** [highslide-software/highcharts.com#2422]
When selecting a range (according to ```zoomType```) and the user is 'mistaken', he should be able to cancel this operation.

**Comment by adamyonk** [comment]
I agree with @iweindesmedt, it would be nice if you could cancel the drag so that the `selection` event never fires. Is there a way to get to the jQuery `drag` event to cancel it in-flight?

**Comment by highslide-software** [comment]
Here's a generic piece of code that doesn't require modification of the Highcharts configuration. It drops the selection on all charts in the page when hitting escape. Note that it doesn't run inside jsFiddle because the key event is not passed down to the iframe. To test it, you need to either add it to a standalone page, or run jsFiddle with a user account then run jsfiddle.net/draft.

[View the jsFiddle](http://jsfiddle.net/highcharts/72gA7/7/).

**Comment by iweindesmedt** [comment]
this seems to work nicely (in the jsfiddle as well: first click below the chart in the iframe, so that the iframe receives focus instead of the source editor).
thanks for the effort! maybe consider adding that ```cancelDrag``` to Highcharts?

**Comment by adamyonk** [comment]
@highslide-software perfect! Thanks so much!
