### ISSUE TITLE
Using exportChart() And Setting Title Ignores HTML Tags

### ISSUE THREAD

**Issue by wergeld** [highslide-software/highcharts.com#2473]
When we export the chart and set the title to a new value that contains HTML items (div tags, etc) and set useHTML: true the chart ignores all tags and uses default formatting for titles.
Here is a jsFiddle with representative issue:
http://jsfiddle.net/wergeld/3FuA4/

**Comment by borys-p** [comment]
Is this patch going to be merged with the main release or it's still an experiment?

**Comment by highslide-software** [comment]
It's still an experiment. I recommend you use the snippet. If it works for you, then go for it.

**Comment by bkfunk** [comment]
One weird thing I'm coming across is that, with `allowHTML: true` if checking for export in a `load` event callback `this.options.chart.forExport` will be the inverse of what it should be (well, actually, `false` when it is exporting, and `undefined` otherwise).

Seems like it's from here:
https://github.com/highslide-software/highcharts.com/blob/15d18f28eddd100367523c8c78d42361d6219952/js/modules/exporting.src.js#L296

Not sure if this is a bug or something necessary for the workaround. You can just test for `undefined`, but that might not work in the future, I'm guessing.

**Comment by highslide-software** [comment]
Yes it's a good point. Highcharts internally uses `forExport` only to disallow `useHTML` in the chart, so your case is an unwanted side effect. But it poses a problem since we have recommended this test ourselves previously.

**Comment by pawelfus** [comment]
It will be problematic to use `allowHTML` especially when adding series in `load` event. Compare exported images:

- with `allowHTML`: http://jsfiddle.net/50g91p9s/
- without `allowHTML`: http://jsfiddle.net/50g91p9s/1/

Quite common use case: loading data after chart is ready and space is reserved for a chart.
