### ISSUE TITLE
drilldown - pie chart

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2911]
In case when we click on the any slice, we receive this error: 

Uncaught TypeError: Cannot read property 'options' of undefined

Additionally the 3rd tier drillUpButton text is not valid (seems like I need to add an id to my all state series).

Example: http://jsfiddle.net/wergeld/wRuW7/

**Comment by pawelfus** [comment]
I think the problem is in `allowPointSelect` option. At the same time, Highcharts are trying to select slice and to drilldown. I guess, drilldown should prevent default action in that case. 

Workaround may be to set `allowPointSelect` option to true only for series which are the most down n the tree (leafs): http://jsfiddle.net/wRuW7/3/ (or the opposite, enable by default, but disable for series with drilldown).

Regarding `drillIUpButton` - according to [the docs](http://api.highcharts.com/highcharts#lang.drillUpText), by default it's `{series.name}`, while second level of drilldown doesn't provide such info. Fixed demo for "Outside State": http://jsfiddle.net/wRuW7/4/

**Comment by highslide-software** [comment]
Thanks @pawelfus!
