### ISSUE TITLE
Error clicking on legend item in heatmap that uses a dataClasses colorAxis & legendItemClick not fired

### ISSUE THREAD

**Issue by steakchaser** [highslide-software/highcharts.com#3444]
I've constructed a modified version of one of the heatmap demos that uses dataClasses for the colorAxis.  There are two issues here:
1. When you click a legend item (red, yellow, or green in example) you get an "Uncaught TypeError: undefined is not a function "
2. There does not appear to be any way to override the legendItemClick event (maybe related to #2833)

Fiddle: http://jsfiddle.net/tjmoretto/2mvfgh99/

**Comment by pawelfus** [comment]
Regarding error, it's fixed on the master branch: http://jsfiddle.net/2mvfgh99/4/
There is no `heatmap.events.legendItemClick`, because `colorAxis` doesn't belong to one series, but is shared between all connected series. Also, it can hide **part** of the points (like in the demo above), not the whole series.

Also, we don't have implemented any events in `dataClasses`, [API](http://api.highcharts.com/highmaps#colorAxis.dataClasses).

**Comment by sebastianbochan** [comment]
Fixed since 4.1.8

**Comment by martin-eq** [comment]
Is this fixed? I'm looking at different solutions but none of them seems to work with colorAxis

**Comment by TorsteinHonsi** [comment]
Live demo please?

**Comment by berdejitendra14** [comment]
Hi Team, 

I am facing the same issue and legendItemClick does not work as expected. Also, the example shared by @pawelfus also fires an event. Does anyone have a solution to this?

**Comment by pawelfus** [comment]
*Internal note:*
Comment above reported as #9246

**Comment by pawelfus** [comment]
Hi @berdejitendra14 

Please see my answer #9246 I was working for a workaround for you..
