### ISSUE TITLE
Your errors give broken links

### ISSUE THREAD

**Issue by fresheneesz** [highslide-software/highcharts.com#3688]
E.g.:

* www.highcharts.com/errors/17

Also, even if the links weren't broken, they give absolutely no context. These are really bad exception messages.

**Comment by highslide-software** [comment]
The link above is working, it points to a page explaining the "Requested series type does not exist".

Even if it's working, your bug report gives no context... What are you missing from our exception messages? Live demos? Code examples?

**Comment by fresheneesz** [comment]
It was a broken link when I posted this. Why not put the exception message in the code itself? Appropriate context would be, for example, the requested series type that doesn't exist. Anything would be helpful.

**Comment by highslide-software** [comment]
> It was a broken link when I posted this.

Okay, probably server downtime then. It doesn't happen too often, we're using CloudFlare and Amazon.

> Why not put the exception message in the code itself?

Because we want to keep file size to a minimum so that your web page loads as fast as possible on slow connections. Preloading all error messages would be a waste of bandwidth for your users.

> Appropriate context would be, for example, the requested series type that doesn't exist.

I agree, but it would also complicate logic and add filesize,  and we're really trying to keep the footprint at a minimum.

**Comment by fresheneesz** [comment]
@highslide-software And what about a developer version (vs production version) then? That's pretty standard.

**Comment by highslide-software** [comment]
Yes that's an idea. We could write up a JavaScript file that you add to
your page and that gives the error messages directly in the console. ​
