### ISSUE TITLE
clipRect doesn't resize after using legend

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3711]
Example: http://jsfiddle.net/4hko262b/1/

Hide one of series using legend, second one is cut off. 

Workaround: Use Highcharts with enabled options for Highstock. Demo: http://jsfiddle.net/4hko262b/2/

**Comment by AaronSleadd** [comment]
Any ideas when this will be fixed? When there is a fix, is it possible to provide a patch of highstock v. 2.0.4 that includes the fix? Thanks!

**Comment by highslide-software** [comment]
Same cause as #3451, which is fixed in dev branch. See http://jsfiddle.net/highcharts/4hko262b/3/.

Try applying these two patches to Highstock 2.0.4: 
* https://github.com/highslide-software/highcharts.com/commit/cd14a97567ee96983f2f92f2020f3f78470b4427.patch
* https://github.com/highslide-software/highcharts.com/commit/cbcbecbd55466fd8385883fb40c0b67f17b15f31.patch
