### ISSUE TITLE
Highchart: Internal Server error NOW

### ISSUE THREAD

**Issue by jimilsumra** [highslide-software/highcharts.com#3741]
Hi,

I have an issue today with highchart as their export server is sending me Internal Server Error and my call is fall into error. So I checked with their export.highcharts.com & select option SVG and then try to see the preview and I got Internal Server Error same error at the moment so can anyone know how it going to resolved?
Thank you in advance.:)

**Comment by gvaartjes** [comment]
Thanks for reporting! We had an issue with posting multipart data to the export server. We fixed this last week.

**Comment by maheshjag** [comment]
@gvaartjes we host our own exporting server, but noticed that the change in enctype from urlencoded to multipart formdata in Higcharts 4 broke our server. Is this documented somewhere?

**Comment by gvaartjes** [comment]
Hi, 

Highcharts it's export module has always used enctype: 'multipart/form-data' for as long I can remember. This hasn't changed with the release of Highcharts 4.0.
What I was referring to in this issue was related to implementing a feature for harnessing against XSS vulnerability.

Best regards,

Gert Vaartjes
