### ISSUE TITLE
Broken 3D Pie chart on 100 depth,  inner size 30% with one value

### ISSUE THREAD

**Issue by salunkenagesh14** [highslide-software/highcharts.com#3745]
3D Pie chart looks broken on the following configuration

innerSize : 30%
depth : 100
startAngle : 180
http://jsfiddle.net/xdwb08xf/

**Comment by salunkenagesh14** [comment]
What is the resolution for this issue ?

**Comment by salunkenagesh14** [comment]
Any updates on this ?

**Comment by pawanvjadhav** [comment]
Anyone working on this from Highchart 3D ?

**Comment by highslide-software** [comment]
@pawelfus Will you have a look at this?

**Comment by pawelfus** [comment]
Two things I'm not sure about:

- unit test for such case, will be checking bounding box enough?
- previously, 3d pie only rendered front of the slice, but as we can see, there are cases when we need to go around the slice. I tried to minimize added code, but it would require more refactoring. I thought about changing logic for rendering pie slice's sides: use `each` to create quarters and later concat them.

**Comment by highslide-software** [comment]
Nice artwork!

> unit test for such case, will be checking bounding box enough?

Not sure. Is there anything else you can check, like the existance of a straight line in the path, or something like that? Otherwise, you could also add a visual automatic test.

> previously, 3d pie only rendered front of the slice...

It's okay. We are very cheap about adding code to the core, meaning the main `highcharts.src.js`. But 3D charts is extended functionality, where the implementer accepts that something extra is loaded in order to draw the 3D charts. So we need to add the code needed to make it work like expected.

**Comment by pawelfus** [comment]
Thanks! It was second time when I needed to understand again how it works so I decided to add short explanation for future cases.

Regarding tests - bounding box won't work, in fact there is a problem how shape is rendered:

Current: 
![screen shot 2015-10-21 at 4 37 12 pm](https://cloud.githubusercontent.com/assets/1453926/10639758/207ed6a0-7812-11e5-8789-c7d73d90dd7e.png)
Bugfix:
![screen shot 2015-10-21 at 4 37 38 pm](https://cloud.githubusercontent.com/assets/1453926/10639759/2080f8b8-7812-11e5-85f9-a4d379193b1c.png)


I think visual test, indeed, would be the best for that case..
