### ISSUE TITLE
Highstock: plot bands disappear when zooming in so that the plot band from date is no longer visible

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3797]
This has been fixed (https://github.com/highslide-software/highcharts.com/issues/2361) in github version of Highcharts, but it is still an issue in Highstock.

Example for x axis bands: http://jsfiddle.net/my7zu/1/
Example for y axis bands (i.e. lower green band): http://jsfiddle.net/1d13tb27/

**Comment by jrnorth** [comment]
I'm experiencing this problem with Highstock as well.

**Comment by krawalltimmy** [comment]
I believe it's because of the min and max value of the x axis. I have two plotbands.
Plotband One (the green one in the screens) goes from xaxis min to a random date. Plotband Two (the red one) goes from the random date to the xaxis max. 

When I didnt zoom (zoom level all) I can see both plotbands.
![xaxis_all](https://cloud.githubusercontent.com/assets/7881356/6347488/c1072296-bc18-11e4-976c-126b24b6fac0.PNG)

When I zoom in in the middle of the chart so I cant see xaxis min or xaxis max both plotbands disappear.
![nogreennorredplot](https://cloud.githubusercontent.com/assets/7881356/6347509/c89e6fbe-bc18-11e4-934e-3f4b14306709.PNG)

When I scroll to the left and zoom in til I can see xaxis min AND my random date, I can see the green poltband.
![onlygreenplot](https://cloud.githubusercontent.com/assets/7881356/6347511/cec3d348-bc18-11e4-8684-5a4e868d6a61.PNG)

When I scroll to the right and zoom in til I can see xaxis max AND my random date, I can see the red plotband.
![onlyredplot](https://cloud.githubusercontent.com/assets/7881356/6347518/d1e8ad96-bc18-11e4-8869-09bc8192f50f.PNG)

It seems like zooming in changes the min and max values of the xaxis and this causes the error.

**Comment by highslide-software** [comment]
Live demo please?

**Comment by krawalltimmy** [comment]
Live demo here http://jsfiddle.net/vgnx2f4z/

**Comment by highslide-software** [comment]
Fixed with #3882 (duplicate). See http://jsfiddle.net/d3c7otn4/ for your fixed sample.
