### ISSUE TITLE
Drilldown issue

### ISSUE THREAD

**Issue by wojcikstefan** [highslide-software/highcharts.com#3806]
Hi @highslide-software, I'm a developer at Elastic Inc., taking over @philfreo.

See the fiddle: http://jsfiddle.net/pypaq94t/17/

You create a 'click' handler in https://github.com/highslide-software/highcharts.com/blob/master/js/modules/drilldown.src.js#L574. I believe it should also be cleaned up in https://github.com/highslide-software/highcharts.com/blob/master/js/modules/drilldown.src.js#L583.

**Comment by wojcikstefan** [comment]
Hi @highslide-software, just following up. Any word on this?

**Comment by wojcikstefan** [comment]
Congrats on the 4.1 release! Did you get a chance to look at this issue by any chance?

**Comment by highslide-software** [comment]
Sorry for the delay! It's a bug allright, it can also be seen at http://www.highcharts.com/demo/column-drilldown. Will fix it ASAP.

**Comment by wojcikstefan** [comment]
Thanks for the fix @highslide-software. Unfortunately, I'm afraid it's not optimized for a multi-series drilldown scenario, where one of the points has `drilldown === false`. See the fiddle: http://jsfiddle.net/pypaq94t/18/. Even though 2 points for Texas have the drilldown enabled, the category is inactive.

**Comment by highslide-software** [comment]
I addressed this in the commit above. The label is now marked as drillable. Another issue also arose: in your fiddle, after my instructions, you count up to 3 async series before you run the drilldown. But the Texas label only holds two points. So I added an event argument, `e.points`, that you can count in order to know how many drillable points/series are associated to the label.

**Comment by wojcikstefan** [comment]
Thanks a lot, works great!
