### ISSUE TITLE
Bar dataLabels positions in 4.1.x - Firefox

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3842]
4.1.1: http://jsfiddle.net/p3dkefgx/1/
4.0.4: http://jsfiddle.net/p3dkefgx/2/

In Firefox dataLabels are misplaced. Of course, I can set `allowOverlap: false`, but still issue exists only in Firefox.

![screen shot 2015-02-18 at 11 23 27 am](https://cloud.githubusercontent.com/assets/1453926/6245592/9e41d54c-b760-11e4-9bf2-11e0bf6e942d.png)

**Comment by highslide-software** [comment]
It is an issue with the `textShadow` style: http://jsfiddle.net/p3dkefgx/3/

**Comment by highslide-software** [comment]
The base cause is the Firefox reports a different bounding box depending on whether the label has a textShadow: http://jsfiddle.net/wvzyrusf/

Chrome does no such differentiation.

In the provided demo, this only affects the positioning of some labels, not all. The labels that are _not_ affected, are the ones with three digits, because these use a cached bounding box that was generated when the `500` axis label was placed.
