### ISSUE TITLE
On line graphs tooltips are not properly hidden when moving from point to point

### ISSUE THREAD

**Issue by PsychodelEKS** [highslide-software/highcharts.com#3921]
http://jsfiddle.net/PsychodelEKS/avnafbrt/3/

In the example, move the pointer over middle black point, it shows the tooltip, if moving pointer straight up, I expect the "black" tooltip to be hidden and "blue" point to be highlighted and corresponding tooltip to be shown, but actually the tooltip is hidden only if leaving plot area (mouse over title), or hovering over other blue line points, otherwise other black dots are highlighted when pointer moves from right to left. Seems like mouseleave not fired when leaving point to tooltip.

I'm not quite sure it's a bug, but playing around with different options did not help, though i may be missing something.

**Comment by highslide-software** [comment]
It's the same issue as #1686, can't run `onMouseOut` when entering the tooltip, because when the tooltip is subsequently hidden, it won't trigger an event on the underlying element. But this was a problem mainly for pies, and there we overcame it by adding the `followPointer` logic. So it may be time to remove the whole logic. 

What do you think of the behaviour here? http://jsfiddle.net/highcharts/avnafbrt/5/

It hides the tooltip, but a consequence is that when you move your pointer above the upper series and let the tooltip fade out, the mouseover on the upper series isn't fired.

**Comment by PsychodelEKS** [comment]
It definitely looks better, though, may be some extra check (or even optimum value realtime  calculation) for tooltip.snap value should be added, because setting it to 50 for the example breaks functionality - "lower" points closer than .snap will be almost not selectable.
As for the bug, what if trigger mousemove for the plot "manually" after hiding tooltip on mouse out, for the underlying element to work?
The best solution as for me, would be to have graphs layer to be under tooltips layer and all the trigger layers (graphs phantoms) to be the top most, so that tooltips do not cover lines trigger zones, that would make such things more straightforward as I see it from here.

**Comment by pawelfus** [comment]
How about new logic since 4.1.5 for tooltip: http://jsfiddle.net/avnafbrt/6/ ? It looks like meeting the requirements from the ticket, @PsychodelEKS could you confirm?

**Comment by PsychodelEKS** [comment]
@pawelfus looks pretty solid for me, definetely better than it was.

**Comment by pawelfus** [comment]
Ok, so closing this ticket for now. If you find any issues, let us know.
