### ISSUE TITLE
 Macbook Pro retina: compressed y axis - too much ticks

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3935]
Here fiddle that gives compressed axis: 

1. On the Mac, set your system time to "Adelaide, Australia" (only valid when DST applies)
2. Open http://jsfiddle.net/2kne1nd8/12/

This is a retina only specific issue:
Firefox, Chrome: does not work
Safari: works

On PC everything works just fine.

Setting y axis to numeric type prevent this error.

___
Edit: Added step 1 above

**Comment by jberzins** [comment]
Defects on Macbook Pro Retina Chrome, FireFox:
1. Multiple generated labels
2. The graph is compressed into last 5% of area
3. xAxis 00:00 is displayed in wrong position, also not visible on Windows Chrome
![chrome-nok](https://cloud.githubusercontent.com/assets/292368/6499604/244bdc2a-c34e-11e4-864b-a28cad1d049b.png)

Expected result as on Macbook Pro Retina Safari same as on Windows:
![ok-safari](https://cloud.githubusercontent.com/assets/292368/6499623/8e35df3c-c34e-11e4-9a27-ab327d76d803.png)

Created a workaround http://jsfiddle.net/n7cttanb/5/
* Uses numeric instead of datetime
* Overrides labels, tooltip to simulate datetime behavior on Windows
* Manually adjusts x axis starting point to simulate datetime default behavior on Windows

Unfortunately do not have Retina Mac myself to debug and identify the cause. Seems related to how milisecond/datetime conversion is implemented.

cheers,
jb

**Comment by highslide-software** [comment]
Can't reproduce it... @KacperMadej Does it requrie a specific width of the chart?

**Comment by jberzins** [comment]
If I give the fiddle to my colleagues with Mac Book Pro w Retina generated results look like attached screenshots.

Please let me know what additional environment information you would need.
Timezone is Australia Adelaide. Language English.
macbook pro 13” retina 2560x1600. Same on 15" MBP retina.

jb

**Comment by highslide-software** [comment]
What browser and OS versions? My versions are:

- OS X Yosemite 10.10 (14A389)
- Chrome Versjon 40.0.2214.111 (64-bit)
- Firefox 35.0.1

**Comment by jberzins** [comment]
Hi, here you go...

Machine #1: 
* Macbook pro retina, 13-inch late 2013
* OS X 10.9.5 (13F34)
* Chrome Version 40.0.2214.115 (64-bit)
* Firefox 35.0.1

Machine #2:
* Macbook pro retina, 15-inch
* OS X Yosemite 10.10.2
* Chrome Version 40.0.2214.115 (64-bit)

Locale:
$ locale
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=

Full screenshot:
![screenshot 2015-03-06 10 12 47](https://cloud.githubusercontent.com/assets/292368/6518574/ae6a6346-c3f7-11e4-9fff-c617ea622210.png)

**Comment by highslide-software** [comment]
Still no problem here...

@KacperMadej Can you help us debug this? In the Axis object, look for unexpected values for min and max or other properties, and try to find out where they come from.

**Comment by KacperMadej** [comment]
Unfortunately, I'm not able to recreate that issue.

**Comment by jberzins** [comment]
I will debug it some time soon when I get my hands on the MPB.

**Comment by jberzins** [comment]
The issue can be replicated if timezone with daylights savings is set. At the moment for example: Adelaide, Melbourne, Sydney.
HighCharts procedure **getTimeTicks** lower bound jumps one year into past and consequently expanding the range.
'''javascript
minYear = minDate[getFullYear]();
'''

The cause of the issue is a browser defect/effect related to new Date() timezone.
new Date(miliseconds) sets Standard Time timezone.
after date.setMilliseconds(0) is called timezone of the date is changed to Daylight Savings (+1h) and UTC time goes into past.

'''javascript
<html>
<p id="date1"/>
<p id="date2"/>
<script>
var startDate = new Date(621000); 
document.getElementById("date1").innerHTML = 'Date: ' + startDate + '\nUTC Year: ' + startDate['getUTCFullYear']();

startDate.setMilliseconds(startDate.getMilliseconds());
startDate.setSeconds(startDate.getSeconds());
document.getElementById("date2").innerHTML = 'Date: ' + startDate + '\nUTC Year: ' + startDate['getUTCFullYear']();
</script>
</html>
'''

Results from Safari OK:
![testdate-safari](https://cloud.githubusercontent.com/assets/292368/6655603/84379e86-cb54-11e4-9ddf-06c4c8c2dc6d.png)

Results from Firefox FAIL:
![testdate-firefox](https://cloud.githubusercontent.com/assets/292368/6655604/8444d880-cb54-11e4-8cf4-d044a041ed1b.png)

Results from Chrome FAIL:
![testdate-chrome](https://cloud.githubusercontent.com/assets/292368/6655605/84451868-cb54-11e4-9f21-98f01a411b72.png)

On Windows new Date() initializes Daylight Savings zone correctly.

The above example will stop working for Australia in April once daylight savings are over.
