### ISSUE TITLE
plotBands in polar charts should be able to span the origin

### ISSUE THREAD

**Issue by ejain** [highslide-software/highcharts.com#3968]
See example at http://jsfiddle.net/hhh2jwdb/; I'd expect both bands to go through the origin, instead of going the long way or being cut off.

**Comment by stephanevanraes** [comment]
Note, this is caused by line 258 in [RadialAxis.js](https://github.com/highslide-software/highcharts.com/blob/master/js/parts-more/RadialAxis.js)
```javascript
  // Keep within bounds
  from = Math.max(from, this.min);
  to = Math.min(to, this.max);
```

A possible solution would be to extend the bounds to go full circle on both sides, (basicly making it possible to have positions from -360 degrees to 720 degrees).
To go the long way we could add a rule that adds 360 degrees if the `from` is higher than the `to`.

**Comment by pawelfus** [comment]
IMHO blue one is correctly rendered. Since `xAxis.min = 0` then plotBand should be clipped.

**Comment by highslide-software** [comment]
Agreed. In accordance to cartesian plots, plot bands are not drawn outside the axis.
