### ISSUE TITLE
Touch Scroll not working in Windows Phone

### ISSUE THREAD

**Issue by tungpham42** [highslide-software/highcharts.com#4014]
As of Highcharts 4.1.4, the div highcharts-container has the style:
```
touch-action: none;
-ms-touch-action: none;
```
which causes the Windows Phone user not able to touch the chart and scroll.
I suggest replace 
```
none
```
 with
```
auto
```
because that fixed my issue.

**Comment by highslide-software** [comment]
As I can read from the [source code](https://github.com/highslide-software/highcharts.com/blob/v4.1.4/js/parts/MSPointer.js#L73), this only happens when the chart is set up to capture touch events for either zooming or moving the tooltip. 

Since Highcharts 4.1, the default option for [followTouchMove](http://api.highcharts.com/highcharts#tooltip.followTouchMove) is `true`. Try setting this to `false` and see if that works better for you. If it does, we may consider changing the default value for windows touch devices. 

The reason we changed it from false to true in the first place, was that iOS changed from locking the scroll to be able to combine scrolling and touch actions.

**Comment by tungpham42** [comment]
Yes, it does help. Thanks for your prompt reply.

**Comment by highslide-software** [comment]
Reopening this - we still need to decide whether Windows devices should have a different default.

**Comment by tungpham42** [comment]
I vote yes, because the followTouchMove feature is nice on my iPhone and Android.
