### ISSUE TITLE
Click on point event does not work for large heatmap

### ISSUE THREAD

**Issue by yplakosh** [highslide-software/highcharts.com#4052]
I would like to handle clicks on points for large heatmap but click event does not work for my example:
http://jsfiddle.net/3y4qsazu/

I specified handler as following code:
<code>
plotOptions: {
            heatmap: {
                point: {
                    events: {
                        click: function() {
                            alert("Point was clicked!");
                        }
                    }
                }
            }
        }
</code>

**Comment by stephanevanraes** [comment]
The point click event does not work because you are rendering the chart using Canvas and it does not have any SVG elements to capture your mouseclick anymore. 

There are two solutions:
1) Remove the Canvas rendering (slower rendering, slightly heavier on memory use due to all the svg elements)

2) Add a click event handler to the chart itself and find the point within the series.
```javascript
events: {
   click: function (e) {
      // get the clicked point by searching the KD-Tree
      var point = this.series[0].searchPoint(e);
   }
}
```

**Comment by yplakosh** [comment]
But why mouseOver works in this http://jsfiddle.net/Lwt7e9q1/ configuration and click does not? 
Are they handled differently?
