### ISSUE TITLE
3d Semi-donut - wrong rendering

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4088]
Examples: 
- http://jsfiddle.net/2pgad3pp/2/
- http://jsfiddle.net/2pgad3pp/3/

**Comment by pawelfus** [comment]
Works fine since 4.1.9: http://jsfiddle.net/2pgad3pp/4/ (shape rendering - missing parts)
However, dataLabels seems a bit off.

**Comment by pawelfus** [comment]
I added some extra comments (3d-transform logic) and refactoring. I wasn't sure if this is a right place, but I decided to make those as one commit with the fix above.

**Comment by highslide-software** [comment]
> I added some extra comments (3d-transform logic) and refactoring.

Yes, it's the right place. Good comments and refactoring is always welcome.

**Comment by highslide-software** [comment]
@pawelfus While you have 3D data labels fresh in mind - do you have any idea how to solve the positioning at the top and bottom? The labels are too distant to the pie: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/3d-pie-donut/

**Comment by pawelfus** [comment]
That is fixed too: http://jsfiddle.net/r6o7egaj/ - in general, positioning `pie.dataLabels` was missing logic for `beta` angle and was a bit buggy.

I didn't add a test for this bug, since almost every 3d-pie had the same issue and for manual tests (during bug-hunting) I used drag&drop demo to move around the pie (like 3d-scatter one).
