### ISSUE TITLE
Server side rendering of the treemap using the java export server

### ISSUE THREAD

**Issue by daddyg** [highslide-software/highcharts.com#4092]
Hi,

It seems I am unable to render a treemap server side using the java export server and passing in an options string. I am guessing this is because it is a separate module but I cannot find any details on how to include a module when building the export server.

Any help would be greatly appreciated,

Mike

**Comment by mikegodber** [comment]
Further to this, I can see that in the 4.1.4 tag the treemap.js file is present in the converter source, but not linked to in either the highcharts-converter.js file or the ServerObjectFactory.

Is this because it is not yet ready or just a mistake? Just wondering because I would like to use this feature in production soon. It seems to be working for me now I have added the files.

**Comment by gvaartjes** [comment]
It's a mistake that it's not mapped up when we released treemaps
