### ISSUE TITLE
Pie Charts are very slow on chart with large legend if visible status is set on creation

### ISSUE THREAD

**Issue by dejongch** [highslide-software/highcharts.com#4104]
The recent [commit](https://github.com/highslide-software/highcharts.com/commit/39905e1e900dab0f39d8a2098cba1d0c206c3bdc#diff-5d3aad1ab4221eaad4e4ba17c165d2a7) seems to have reintroduce issue #4069 to pie charts that have their [visibility set on creation](http://jsfiddle.net/303080pb/) when the chart is redrawn such as on changing the visibility of an item.

This seems to be the cause because the called to setVisible is passing in true for the force variable which is bypassing the if added in for #4069 

A secondary issue here is looking at the code there doesn't seem to be a good way to disable/enable a large number of pie slices without either causing a redraw for each item or a re-render of the legend.

**Comment by dejongch** [comment]
Is this issue going to be addressed? We won't be able to update to your latest versions until it is.

**Comment by highslide-software** [comment]
Fixed this with ec6f89715b4a0a41d2e71b3d0f06831a21d9f02e.

I did some refactoring that goes all the way back to the pie percentage issue that caused #4069. Also, added a second parameter, `redraw`, to `setVisible` so that you can run a single call to `chart.redraw` at the end. This is similar to other point update methods. See [jsFiddle demo](http://jsfiddle.net/highcharts/303080pb/1/).
