### ISSUE TITLE
pointPlacement isn't working if there is no column type series

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4112]
If pointPlacement is set, but chart has no column series, then pointPlacement is not applied.

Example with column type series: http://jsfiddle.net/mcLoxpur/1/
Without: http://jsfiddle.net/mcLoxpur/

**Comment by highslide-software** [comment]
It requires the `pointRange` to be known. When a column is present, the pointRange is computed. http://jsfiddle.net/highcharts/mcLoxpur/2/.

This information is now added to the docs, http://api.highcharts.com/highcharts#plotOptions.series.pointPlacement

**Comment by drmrbrewer** [comment]
But it seems that pointRange cannot be set per series?  See http://jsfiddle.net/drmrbrewer/pggdnx35/1/ and the comments therein.

**Comment by highslide-software** [comment]
Why would you want different point ranges? The point range only dictates the width of each column, and the position when using pointPlacement. The X values are not affected.

**Comment by drmrbrewer** [comment]
I have a situation where I have a datetime x axis, and am plotting points that start at 1 hour spacing (between this point and the previous), then move to 2, then 3, etc... so the spacing between points in datetime is not constant.  So if I want to plot the points at pointPlacement of -0.5 (i.e. in the middle of the range for the point concerned), then I don't want a single pointRange that applies across the whole chart, for all series.

Initially I figured I'd have to divide my points into different series, according to point spacing.  But that gets awfully complicated, and I'm not sure how to join the line from one series to the next (bridge the gap).  Even worse if it's not a neat progression from 1hr to 2hr etc, but instead the spacings are somewhat more random.

So what I figure now is just to keep them all in a single series, but then I can't use pointPlacement to place my points correctly because of the variable spacing, so instead I am actually plotting them at intermediate positions (i.e. setting x explicitly to the mid point), and deal with the shared tooltip separately (to ensure the tooltip doesn't fire at the intermediate positions).

Ultimately, I would suggest that it would be really neat to be able to set pointRange *per point* or *per series*, so that pointPlacement will look first at pointRange for the point, and if not defined then look at pointRange for the series, and if not defined then look at pointRange for the chart.

That way you can be flexible with pointPlacement when you have data with variable spacing along the x axis.

**Comment by highslide-software** [comment]
I guess the `pointRange` wasn't designed to work like that. You could try resolving it by using categories instead of a datetime axis.

**Comment by drmrbrewer** [comment]
Other than it being something else to implement, is there any reason why it would not be appropriate or logical to have `pointRange` being applicable (optionally) on a per-point basis too?

Incidentally, I think the updated docs (to resolve this issue) is slightly misleading in that the implication is that you can set `pointRange` for the series concerned to what you want.  But when I've played with it (see http://jsfiddle.net/drmrbrewer/pggdnx35/1/), it seems that if you set more than one `pointRange` (in different series), the highest `pointRange` is used.

And the `pointRange` hyperlink in the new docs doesn't point anywhere.

I still think that per-series and per-point `pointRange` would be neat :)  I can't imagine that my use case (see above) is *that* unusual... I'm just plotting points on a datetime axis, where the point spacing is not uniform and where I want the points to be shifted away from 'on' placement.  I can't see how I can use categories as you suggest, if point spacing varies somewhat randomly between points... at least not without a *lot* of hard work.
