### ISSUE TITLE
Treemap: exporting after drill down to lower levels gives wrong data labels

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4136]
Example (demo with exporting): http://jsfiddle.net/172sxe56/
Steps:
1. Click on treemap to get to lower level (or even bottom one)
2. Export to any format
Labels are not used correctly.

**Comment by bladjack** [comment]
any news on ths issue? I have the same problem.

**Comment by sebastianbochan** [comment]
+1

**Comment by jon-a-nygaard** [comment]
Hi, sorry for the late reply.

This issue will be fixed in the upcoming maintenance release (4.1.9). For those who want to fix the issue immediately, please try the quickfix below.

**Quickfix**
Depending on the version of the treemap.src.js file look for this code in either the function *translate* or *handleLayout*:
```javascript
if (this.points.length) {
  ...
  this.rootNode = pick(this.rootNode, ""); // Look for this line
  this.rootNode = pick(this.options.rootId, ""); // Replace with this line
  ...
}
```
Also do the following changes in the function *drillToNode*:
```javascript
drillToNode: function (id) {
  this.rootNode = id; // Look for this line
  this.options.rootId = id; // Replace with this line
  ...
}
```

**Comment by sameerpalsingh** [comment]
@jon-a-nygaard , 
i am using Highcharts JS v5.0.14 (2017-07-28) . Still the problem persists. Once you drill down to second or third level. The download PNG or JPG options generates images of 1st level, not the current level.

**Comment by pawelfus** [comment]
Hi @sameerpalsingh 

Thank you for reporting the issue. It's a different issue (this one is about wrong dataLabels), so I reported this as #7991 Thank you once again!
