### ISSUE TITLE
datetime xData values are wrong when turboThreshold not exceeded

### ISSUE THREAD

**Issue by kdwink** [highslide-software/highcharts.com#4148]
A line chart with a datetime x-axis where the x values are provided as Date objects will render correctly or not depending on the value of turboThreshold for the series.

http://jsfiddle.net/36f85yz4/

When it renders incorrectly the xData values (which should be dates) are somehow converted to integers: 0, 1, 2, 3... and consequently the chart renders dates starting at year zero, month zero, etc.

Documentation seems to indicate that turboThreshold is an optimization and should not have this affect. 

I hit this bug when plotting a number of data sets with points numbering around turboThreshold default (1000).  Those with fewer points rendered wrong, those with more correctly.

Tested on linux using latest version of chrome.  Behavior is present in highcharts 4.1.5, 4.0.4, and latest master.

**Comment by highslide-software** [comment]
It gives unpredictable results because your X values are misconfigured. According to [the API](http://api.highcharts.com/highcharts#series<line>.data.x), x should be a number. For datetime axes, the X value is the timestamp in milliseconds since 1970. What you are passing in is Date objects, not integers. See http://jsfiddle.net/36f85yz4/1/.
