### ISSUE TITLE
Tight column chart and shared tooltip results in unresponsive tooltip

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#4200]
Steps to reproduce:
1. Open http://jsfiddle.net/highcharts/fdhnde3b/3/
2. Hover the mouse quickly over the columns, and observe that the tooltip doesn't follow the cursor as it should. 
3. Also observe that the tooltip follows quickly when hovering above the columns.

For reference, it follows quickly when the tooltip is __not__ shared: http://jsfiddle.net/highcharts/fdhnde3b/4/

In Highcharts 4.0 it worked as intended: http://jsfiddle.net/highcharts/fdhnde3b/5/

**Comment by highslide-software** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/fdhnde3b/6/

**Comment by furkankatman** [comment]
Hi friends , I would like to make a point clearer about this TIGHT COLUMNS since I almost consumed one day about how to make my columns tight and width of 20px .I browsed so many links and all I find was pointing " groupPadding , and pointPadding  " and those are valid unless you have many columns that fills the chart well. But if you have few columns then your columns get seperated . And finally I found a solution to this by using "pointPlacement" property of series arrays.And here I provide the Plunk for you  to see results. Results: http://plnkr.co/edit/uqZ4LEugMefLD6WSzHZT?p=preview  
Take care.
