### ISSUE TITLE
Radial gradient is not printed from center - pie 3d

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4203]
Let's compare
- http://jsfiddle.net/w8pdszbu/
- http://jsfiddle.net/ojz8m06x/

In second one, gradient should be single and printed from center

**Comment by highslide-software** [comment]
@stephanevanraes In PieSeries.js, there is a line that [sets the radial reference](https://github.com/highslide-software/highcharts.com/blob/v4.1.5/js/parts/PieSeries.js#L440) to the center of the pie rather than the center of the slice. Can you check if it is relatively easy to apply this to the top shape of the 3D pies as well?
