### ISSUE TITLE
Negative column chart - threshold null works incorrect

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4233]
Let's compare:
1) Positive values are printed properly: http://jsfiddle.net/nabyy31s/7/
2) Negative are wrong: http://jsfiddle.net/nabyy31s/6/
3) Desired effect: http://jsfiddle.net/nabyy31s/9/

**Comment by sebastianbochan** [comment]
Is not an issue, because null value prints element from low level. Workaround: http://jsfiddle.net/nabyy31s/13/ using a tickpositioner.

**Comment by highslide-software** [comment]
@hmha commented:

> Case:
> 
> threshold: null
> realMin: -15000
> realMax: 15000,
> 
> so combination of negative and positive. It sets threshold to realMin, what causes columns to be drawn > from realMin, what does not look correct..

This reveals an inconsistency with the fix above. What he wants here is actually to preserve the threshold at zero, but he doesn't want the Y axis extremes to be affected by it. Perhaps we need another option that deals directly with the Y axis extremes.

**Comment by KacperMadej** [comment]
Right now if `threshold` is set to `null`, then `realMin` or `realMax` is used depending on `realMax` being smaller than `0`. There is a suggestion from a client, to make mentioned dependency more controllable, so to allow setting threshold to `realMin` or to `realMax`. Now we can get similar effect when setting `threshold` to a value bigger or smaller than series data and setting `softThreshold: true`.

**Comment by TorsteinHonsi** [comment]
@KacperMadej My head just went poof :) Can you show this with a fiddle?

**Comment by KacperMadej** [comment]
@TorsteinHonsi Yes, sure - I will try to explain this better:

In [threshold's API reference](http://api.highcharts.com/highcharts#series<area>.threshold) there is: 

> If `null`, the area behaves like a line series with fill between the graph and the **Y axis minimum**.

This is not always true.
Example 1 - zoom into last point and area will flip: http://jsfiddle.net/b7ecq6c7/
Example 2 - fill is not between the graph line and Y axis min: http://jsfiddle.net/b7ecq6c7/1/

This because `axis.max` becomes (1) or is (2) `< 0`.

The client wanted for `threshold: null` to be like described in API, so for (2) this should look like:
Example 3: http://jsfiddle.net/b7ecq6c7/2/

This can be done by `threshold: -Number.MAX_VALUE, softThreshold: true`, but it seems more like a workaround. Maybe there is a room for a setting that would allow the same effects as `softThreshold: true` and:
 * `threshold: Number.MAX_VALUE` - always up
 * `threshold: -Number.MAX_VALUE` - always down (well according to API `threshold: null` should do that)
