### ISSUE TITLE
Pie Chart with all 0 values draws a vertical line

### ISSUE THREAD

**Issue by dejongch** [highslide-software/highcharts.com#4246]
http://jsfiddle.net/04u6dexn/

I think that it would be better to just show nothing then to show a 0 width pie slice.

**Comment by highslide-software** [comment]
But there actually is data...

**Comment by Johnb21** [comment]
Nulls provide the same result

http://jsfiddle.net/n9wLhfo7/

**Comment by pawelfus** [comment]
In my opinion, when your data can contain null/0 values then you shouldn't be using pie chart to display such data. Instead bar/column types are better choices. I know, chart should fit the design, but that's similar case to rendering negative values on the pie chart. Charts shouldn't be only "nice" but informative in the first place. 

Of course, when you still need to create pie chart, then I suggest to filter out corrupted data.

**Comment by highslide-software** [comment]
I agree with @pawelfus, however there are cases when the implementer doesn't have control over the incoming data, and then Highcharts should handle it as gracefully as possible.

My proposal is that we draw the border for 0 values, but do not draw it for null. Because 0 is acutally data, but null is not. The question is what to do with the data labels. Should we keep the data labels for null values, or should we hide those too?

**Comment by pawelfus** [comment]
How about using the same solution as for column with null values? Where you can control label in the formatter, like displaying nothing or "N/A".

**Comment by highslide-software** [comment]
Yes, good point. Will do that.

**Comment by kamilkulig** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Why the +1 @kamilkulig ? This issue was closed two years ago, is there a new fail case for it?
