### ISSUE TITLE
Treemap - point.event triggered only on first time

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4261]
Click event is triggered only first time, but after drillup is missing.

Example: http://jsfiddle.net/7j03wx33/5/

**Comment by jon-a-nygaard** [comment]
All click events was removed when only the click event for drillToNode should be removed.
This issue is fixed in the next maintenance release, alternatively use the quick fix below.

## Quickfix:
Go to the function drillTo on line 685 and replace the following code:
```javascript
//Replace this code
H.removeEvent(point, 'click');
// with this code
H.removeEvent(point, 'click.drillTo');
```
And thereafter go to line 703 in the drillTo function and replace with:
```javascript
// Replace this code
H.addEvent(point, 'click', function () {
// with this code
H.addEvent(point, 'click.drillTo', function () {
```
