### ISSUE TITLE
Axis.breaks with null points inside the break

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4275]
Not sure if a bug, but interesting issue. 

Background: we have data and some null points. We want to break line where null points are created (`connectNulls` set to false). And we want to use break on the axis to remove that null points. Expected result is broken line where null exists with axis break. It will work similar to `gapSize` but with better control over the space. 

Now let's compare examples:

- http://jsfiddle.net/952u2bh5/7/ - almost expected, just line is connected over the break. I know, only points 6-7-8-9 are nullified, and all of them are **inside** the range, so it kind of works fine. 
- http://jsfiddle.net/952u2bh5/6/ - break split into two breaks, works better, but problem with labels overlapping

Is there any better solution for such case? I mean, "end" line on axis break starting points, and "start" line on the ending of break. What I want to say that actual behavior is fine (IMHO), but as example above shows, sometimes it requires different result. 

Maybe option for breaks like `connectBreaks` or something similar to control this would be good solution?

**Comment by AnvilStriker** [comment]
Thanks, Pawel, for opening the ticket -- I'm the one who was [moaning about this on StackOverflow](http://stackoverflow.com/q/30739641/1337498). :-)

To put the requirement simply: there are times that one will want points at the boundaries of a break to display as connected, and times that one won't. 

My failed approach of trying remove the line segment spanning the break by setting all point values within the break to `null` was an attempt to leverage my existing understanding of how `connectNulls` works in charts that don't have breaks. 

The fact that it didn't work seemed counterintuitive to me because, in my mental model, a break in the chart is something that happens at the "presentation layer," and is not something that ought to affect the *interpretation* of point values in a region marked as a break. In other words, the fact that we're suppressing display of the markers for those points *shouldn't* mean that their values become totally meaningless, or that they should be ignored for any other effects they might have on the chart. To the extent that a `null` value results in omission of a marker *and* the line segments that terminate on that marker in a normal chart (with `connectNulls` set to `false`, of course), my intuition tells me that the same behavior should occur, as much as possible, for points that fall within a break.

Of course, if one really follows the above logic, and gets down to analyzing cases like "some points null within the break and others not," we then might have to think about whether we'd like to see *partial* line segments sprouting out of one or both markers at the boundaries of the break, what slopes such partial segments should have, etc... and maybe the implementation becomes over-complicated.

So I could certainly live with a simpler solution such as your suggested `connectBreaks` option, as long as I could apply it on a break-by-break basis -- because in a single chart I *might* want some breaks connected, and others not.
