### ISSUE TITLE
HighCharts Export PDF - Second blank page & blurry legend

### ISSUE THREAD

**Issue by marcellodonvito** [highslide-software/highcharts.com#4283]
JSFIDDLE: http://jsfiddle.net/MarcelloDonvito/37LbaLk5/1/

Hi, when I'm exporting a chart as a PDF there's always a second blank page.
According to [this] (http://forum.highcharts.com/highcharts-usage/exporting-second-page-blank-t28770/) when I set a value to the width property the second page won't rendered, **but with this fix the legend appears as blurry when the navigation is activated**.

According to the [documentation] (http://www.highcharts.com/docs/export-module/render-charts-serverside) the width property overrides the scale parameter, but the default value of the scale parameter works fine for the legend.

Is there another solution to manage the second blank page?

Thanks.

**Comment by highslide-software** [comment]
The second blank page seems to appear when there is an unfortunate combination of width and height of the chart. Your chart is 700px by 500px. Making it only 1px higher works around the issue: http://jsfiddle.net/highcharts/tyLfoe5r/

**Comment by highslide-software** [comment]
I did some systematic testing with widths against heights, and the resulting pattern is interesting. It looks like the bug is more likely to appear with lower withs, which indicated that is isn't only an issue with the aspect ratio:

|   | 697  | 698  | 699  | 700  | 701  | 702 |
| --- | --- | --- | --- | --- | --- | --- |
| 496 | ok   | ok   | ok   | ok   | ok   | ok |
| 497 | fails | ok   | ok   | ok   | ok   | ok |
| 498 | fails | fails | fails | ok   | ok   | ok |
| 499 | fails | fails | fails | fails | ok   | ok |
| 500 | fails | fails | fails | fails | fails| ok |
| 501 | ok    | ok   | ok    | ok    | ok   | ok |
| 502 | ok    | ok   | ok    | ok    | ok   | ok |
| 503 | ok    | ok   | ok    | ok    | ok   | ok |

**Comment by marcellodonvito** [comment]
Hi, I apologize for my delay in responding.

So one solution is to fix the height and the width of the chart, without modify the default values of the exporting property. Maybe I can use those fixed values that you have listed.
