### ISSUE TITLE
pointBreak not called for negative values

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4356]
Example: http://jsfiddle.net/kzLon27v/3/

Last column didn't render required break-mark, because callback isn't fired. The problem appears only when value is lower than break.

**Comment by highslide-software** [comment]
The problem lies in [these lines](https://github.com/highslide-software/highcharts.com/blob/v4.1.6/js/modules/broken-axis.src.js#L295-L301) of the broken-axis module. 

The current implementation only takes positive columns into account. While it currently only checks if the value is below the break, what is should check is if the value is between the threshold and the break.
