### ISSUE TITLE
Tooltip bug with stacked column chart

### ISSUE THREAD

**Issue by mujahidq** [highslide-software/highcharts.com#4372]
Hello,

Hoping you can help with this. i am not sure if this is a bug in the source code.

http://jsfiddle.net/js55fuo1/24/

Notice the tooltip change when you move around the column. It should stay the same unless you move to another column. 

Please help

Thanks!

Mujahid

**Comment by highslide-software** [comment]
Hi Mujahid,

You're hacking into the column series.drawPoint method and modifying the position of the columns, that's why you get unexpected results. You can set tooltip.shared to false to prevent this, but then you need a new tooltip formatter, and also to set new tooltipPos on the point (internal code). http://jsfiddle.net/highcharts/js55fuo1/35/

**Comment by mujahidq** [comment]
Yes i think its better to set the shared to false and update the formatter.

Thank you Sir!

**Comment by mujahidq** [comment]
This worked thanks. But is there a right way to do what i am doing? Am i
missing setting something. I noticed that the zooming feature is also a
little wierd when i go over 3000 points. Like if i zoom in 2x times then
the bars disappear on the right hand side.

Thanks!

**Comment by sebastianbochan** [comment]
Please post your demo.
