### ISSUE TITLE
Area chart - tooltip not displayed for each point

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4392]
Example: http://jsfiddle.net/so4dbdqL/10/

**Comment by gvaartjes** [comment]
Closing as being unconstructive

**Comment by pawelfus** [comment]
Further description:

Hover first point on the chart (bottom one). Displayed tooltip for a second points (with the same timestamp). 
Hover third or fourth point - tooltip displayed only for a fifth point etc.

**Comment by highslide-software** [comment]
This happens because there are multiple points on the same X value. The tooltip on line-type series is set up to search for the closest point only in the X direction, in order for shared tooltips to work and for optimized tooltip behaviour with multiple series. 

You can override that by modifying the area series prototype: 

```js
Highcharts.seriesTypes.area.prototype.kdDimensions = 2;
```

[View live jsFiddle](http://jsfiddle.net/highcharts/so4dbdqL/11/).
