### ISSUE TITLE
Highmaps colorAxis and series colors overlapping on resize

### ISSUE THREAD

**Issue by RadValentin** [highslide-software/highcharts.com#4397]
#### Issue Description
Setting `colorAxis` for a chart as well as individual colors for each series `data` will cause the chart to  initially render the series color but on resize it will switch to `colorAxis` colors. Furthermore, hovering over the chart will cause it to revert to the initial colors.

![geomap_resize](https://cloud.githubusercontent.com/assets/3300066/8727323/b88c5cbe-2be7-11e5-9a80-04e2ca1e68b8.gif)

#### Notes
- [jsFiddle Demo](http://jsfiddle.net/valentin/2mss9wj8/3/)
- Reproduces in: Chrome, Firefox (latest)
- Using Highcharts 4.1.7  and Highmaps 1.1.7
- In Highmaps v1.0.4 the chart would always render series colors when they were present, disregarding `colorAxis`

**Comment by pawelfus** [comment]
Demo on master branch: http://jsfiddle.net/2mss9wj8/4/ 
I'm curious - what is the expected result? I guess, since points have colors, then colors from `colorAxis` shouldn't be used. However, in that case detach `colorAxis` from series: http://jsfiddle.net/2mss9wj8/5/

If this should be the opposite, so `colorAxis` should have higher priority than `color` option for a point, then simply remove that `color` options. 

I'm not saying that the above are solutions, just workarounds for a specific cases.

**Comment by RadValentin** [comment]
@pawelfus Thanks for the quick reply. You're right, in the end I chose to go with the solution of not having both `colorAxis` and `color` options. 
Still, it's weird that in a previous version of Highmaps, 1.0.4, this issue didn't happen, point colors had priority.
