### ISSUE TITLE
3d pie chart - cannot disable resize animation

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4404]
Example: http://jsfiddle.net/pryx6j65/6/

In 2d chart, works well: http://jsfiddle.net/pryx6j65/7/

**Comment by pawelfus** [comment]
Internal note:

There are two problems:

- `globalAnimation` is not accessible for highcharts-3d module, since is encapsulated. Probably simple adding to `Facade.js` would be enough. Otherwise higcharts-3d module does know nothing about the animation. 
- animation runs always [here](https://github.com/highslide-software/highcharts.com/blob/master/js/parts-3d/SVGRenderer.js#L274). Instead we should pick between `duration` (why it's called that way?) and `globalAnimation`, then merge with `step` function.

**Comment by highslide-software** [comment]
> animation runs always here. Instead we should pick between duration (why it's called that way? options should be better, I think) and globalAnimation, then merge with step function.

Yes, options would be the correct name.

**Comment by highslide-software** [comment]
This was fixed in the master since refactoring 3D pie slice attribute setters and animation last week. The provided fix in the bugfix branch is now obsolete.
