### ISSUE TITLE
Highmaps tooltip appearing everywhere on the map (regression)

### ISSUE THREAD

**Issue by laurahelde** [highslide-software/highcharts.com#4409]
The simplified version of my situation: I have a map series and a mappoint series on the same map. I need the mappoint series to have tooltips and the map series not to, but I can't use enableMouseTracking: false because I have custom mouse events on the map series.

So I achieved this in version 1.1.4 by putting the tooltip on the map level and checking the series type within the formatter.  If the series type is map it returns false to stop the tooltip from appearing. Here is a fiddle demonstrating with 1.1.4, working as expected: http://jsfiddle.net/b56h9tjo/1/

The same code in the current version is broken: the "Minneapolis" tooltip appears no matter where I hover on the map: http://jsfiddle.net/b56h9tjo/ .  Is there any way to get what I'm looking for without downgrading?

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will have a look at the issue and come back with an answer soon.

**Comment by oysteinmoseng** [comment]
There seems to be an issue with the new way Highcharts handles tooltips (probably commit d228fa0af315d6bc60069e509b31d8c9b44592a4). We'll look into it, but due to vacation time, it could take some time to resolve. For now it looks like the old version (1.1.4) is the way to go, as there unfortunately doesn't seem to be an easy workaround.

**Comment by laurahelde** [comment]
Okay, thanks for the update.  Will go back to 1.1.4 until further notice.
