### ISSUE TITLE
X Axis, align left and x property in a scatter chart - not tested on other types

### ISSUE THREAD

**Issue by keiron77** [highslide-software/highcharts.com#4412]
Aligning the x axis title to the left and adding an x distance doesn't work:

xAxis: {
title: {
enabled: true,
align: 'left',
x: 30,
text: 'Sample Title'
}
}

Results in the text object x value being 'Not a Number':

< text y="437" visibility="visible" style="color:#707070;font-weight:normal;fill:#707070;" class=" highcharts-xaxis-title" transform="translate(0,0)" text-anchor="undefined" zIndex="7" x="NaN" >< tspan >Sample title</ tspan></ text >

**Comment by jon-a-nygaard** [comment]
Hi @keiron77 

The reason why you are getting x="NaN" is because align left is not a valid option. You are most likely looking to use align low. Read more about the options here at [xAxis.title-align](http://api.highcharts.com/highcharts#xAxis.title.align)

Use the options below and your code should work as expected:
```javascript
xAxis: {
	title: {
		enabled: true,
		align: 'left',
		x: 30,
		text: 'Sample Title'
	}
}
```
