### ISSUE TITLE
Resize issue for area chart

### ISSUE THREAD

**Issue by srgothi92** [highslide-software/highcharts.com#4436]
When we try to do resize on area chart an exception (TypeError: Cannot read property 'length' of undefined) is being thrown from jQuery grep method. This error is reproducible on jsfiddle  http://jsfiddle.net/srgothi92/3o4xrjjv/6/ . 
Try to resize the width and height of container in jsfiddle , in console you will see javascript exception being thrown.
It was tested on chrome browser and used highcharts demo area chart code.

**Comment by highslide-software** [comment]
I don't see a JavaScript error in Chrome on Mac. I am dragging the lower right handle. 

Furthermore, instead of rebuilding the chart on resizing, you should use `chart.setSize`: http://jsfiddle.net/3o4xrjjv/7/

**Comment by sebastianbochan** [comment]
You need to drag window, rapidly and very fast.

**Comment by srgothi92** [comment]
Can i know the status ? . We are waiting for this issue to get resolved.
 If you want some extra help from my side please inform.

**Comment by pawelfus** [comment]
@highslide-software This can be reproduced only in the first demo. It comes from `startRecursive()` method. It's indeed caused by destroying and recreating chart when resizing chart. In short, when dragging to the right it works fine, but when you want smaller width, you drag mouse over the chart which tries to find points on destroyed chart. 

@srgothi92 Have you tried to not destroy chart as suggested? Just resize chart using `setSize(w, h)` method?

**Comment by highslide-software** [comment]
Still no go, but @srgothi92 should under any circumstance use `chart.setSize` instead of construction a new chart.

**Comment by srgothi92** [comment]
I have done this changes in my actual code. Thanks for the feedback :)
