### ISSUE TITLE
RangeSelector not behaving as expected when focus lost

### ISSUE THREAD

**Issue by findoo** [highslide-software/highcharts.com#4457]
To replicate:
- Open http://www.highcharts.com/stock/demo/areasplinerange
- Select the end date on range selector
- Tab away or sometimes even just click away from the item without change.
- Open the export menu. 

![highchartsbug](https://cloud.githubusercontent.com/assets/3541918/9201297/229c3528-4044-11e5-901e-4a2e437619b6.png)

**Comment by highslide-software** [comment]
Minimal demo: http://jsfiddle.net/highcharts/Lr9groc8/

It's a regression that appeared in Highstock v2.1.5, introduced with commit 872c94e.

**Comment by romant-1** [comment]
The issue is there again - another regression?
[http://www.highcharts.com/stock/demo/areasplinerange](http://www.highcharts.com/stock/demo/areasplinerange)
Just click one of the range selector input fields, tab away and open the export menu - the input fields will be on top of the export menu as reported originally.

**Comment by pawelfus** [comment]
Thanks! Replied in #10404
