### ISSUE TITLE
yAxis labes problem with align and rotation

### ISSUE THREAD

**Issue by Atte902** [highslide-software/highcharts.com#4468]
Here is example: http://jsfiddle.net/rckgLsv5/

Here you can see, if you set rotation to 0 the last label is not centered. If you align it to left, it goes over the chart, and right it stays there, but other ones goes there too. Also if you set rotation to 1 it will mess up those labels.

The last label goes off position after render and goes back after redraw, but when exporting chart (at least to pdf and png) it is off position.

**Comment by highslide-software** [comment]
With default settings, which are `align: center` and `rotation: 0`, the label is designed to move into the chart area. To prevent that you can set a higher `marginRight` in order to give it more space: http://jsfiddle.net/rckgLsv5/1/.

When you set align: left it will do that, even though it is clipped.

**Comment by Atte902** [comment]
So by default there should not be enough room for the last label? Also is that a bug, when you set rotation to 1 and it will mess up the labels?

**Comment by highslide-software** [comment]
> So by default there should not be enough room for the last label?

By default there is plenty of room to the left, so it doesn't hurt moving it some pixels to keep clear of the right edge. See http://www.highcharts.com/demo/line-time-series for instance.

> Also is that a bug, when you set rotation to 1 and it will mess up the labels?

When setting rotation, the current algorithm seeks to avoid collsion by increasing the spacing. In this case that is not obvious, and it turns out it also adds an ellipsis, to the big spacing isn't necessary: http://jsfiddle.net/highcharts/rckgLsv5/2/
