### ISSUE TITLE
Column dissapearing when trying to display two columns at the same timeStamp

### ISSUE THREAD

**Issue by jprivillaso** [highslide-software/highcharts.com#4470]
I am having a problem when I try to add dynamically two series to a chart, on a same timeStamp and then I set manually the extremes of the xAxis. I want to compare two columns plotted in a same time stamp.

If you hide the "serie2", "serie1" will be displayed. It only occurs when i have one point.

jsFiddle:
http://jsfiddle.net/qyq7xLhg/1/

If I add more points, it will work as expected
jsFiddle:
http://jsfiddle.net/19g913g7/

Thanks.

**Comment by pawelfus** [comment]
Simply your extremes are removing blue series from the view, check: http://jsfiddle.net/qyq7xLhg/2/ - as you can see, blue column is displayed on the left side of your `min`. When you hide `Series 2`, then column is translated to the center of the timestamp, so in your first case renders **part** of the column on the left edge of plotting area. 

Why it works for multiple columns? Because Highcharts are able to calculate distance between two closest points within the same series (it's not easy when have only one point ;) ) and add extra padding. 

When you have just one point per series, and you know min and max for the axis extremes, then calculate `pointRange` and set it, for example in your first demo, it would be good to set point range to one day, see: http://jsfiddle.net/qyq7xLhg/3/

**Comment by jprivillaso** [comment]
Thanks a lot. It solved my problem!
