### ISSUE TITLE
Chrome crashes with bar chart and staggerLines: 1

### ISSUE THREAD

**Issue by MrGuiMan** [highslide-software/highcharts.com#4477]
Hi,

We've got an issue reported in our application that would cause Chrome to crash when setting Intervals on a bar chart. The weird thing about it is that it just doesn't happen on a column chart for instance. 

I've spent some times eliminating options to determine where this could come from and it seems like it doesn't happen if I set staggerLines to 0. I'm having a hard time understanding why this would be the reason but I figured it could give some indications.

Here's a JSFiddle:

http://jsfiddle.net/9Lav4c6p/1/

1) Set the series type to bar and run: Chrome crashes
2) Set the series type to bar and staggerLines of yAxis to 0: Everything works fine
3) Set the series type to bar and remove ticksInterval from yAxis: Everything works fine

Am I doing something wrong ? What should I do to prevent this to happen while keeping that staggerLines options to 1 ? 

Thanks

**Comment by highslide-software** [comment]
With a `tickInterval` of 1 and `staggerLines` set to 1, you're bypassing the default behaviour which is to prevent too many labels from being drawn. With these settings, the browser will try to render 100,000 labels, which doesn't make sense. I recommend that you remove the `staggerLines` setting and let the default algorithm work. 

Also, is there a special reason for setting the `tickInterval` option? The default tick placement usually is better: http://jsfiddle.net/highcharts/9Lav4c6p/2/

**Comment by MrGuiMan** [comment]
Basically we provide our users with Dashboard personalization through widgets , charts being one of them, and let them personalize the options to make the charts look just as they want it, thus setting the tickInterval option.

I could talk about the relevancy of this personalization option in the next meeting, or maybe disabled staggerLines in certain cases, but I'm still wondering why those same two options wouldn't cause any problem for the column chart ? Does the column chart not act as expected ?

**Comment by highslide-software** [comment]
Okay I understand the problem. Highcharts shouldn't crash the browser under any circumstance. In Highcharts 4.0 we had [error 19](http://www.highcharts.com/errors/19) for this case, but in 4.1 we removed that error message because the default behaviour should prevent it. But it seems like setting the staggerLines re-introduces the error. I'll investigate.

**Comment by highslide-software** [comment]
I propose that we do a last minute quality check of the tick positions, so that we avoid having more that one tick per pixel in the chart, which makes no sense under any circumstance. So if your users make this bad choice, we keep only the first and last tick. What do you think of this? http://jsfiddle.net/highcharts/9Lav4c6p/3/.

In my opinion this is a more graceful way of handling it than showing and error message in the console.

**Comment by MrGuiMan** [comment]
I like the way this is handled, It is indeed more graceful and generally makes sense, I feel like this is something that we could explain quite simply to our users. However we still have a difference in behavior between bar chart and column chart.

A quick debugging shows that ticksPosition.length never is above this.len in case of a column chart. In fact it seems like there's some kind of calculation on column chart that just doesn't happen on bar. Any insight ?

**Comment by highslide-software** [comment]
The labels are handled differently between horizontal and vertical axes, as seen in [this code block](https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/parts/Axis.js#L1491-L1520). On a vertical axis we simply skip labels based on the text height, but on a horizontal axis it is more complicated because each label may have a different width. In this case the default behaviour is to add auto rotation, but when your users set staggerLines, this is not performed.

**Comment by MrGuiMan** [comment]
Figured it would be something like this.
Well while it is unfortunate that horizontal and vertical behaves differently, I do understand the implications and the provided solution will do quite nicely !

Thanks a lot
