### ISSUE TITLE
Exporting html tags not working

### ISSUE THREAD

**Issue by Atte902** [highslide-software/highcharts.com#4484]
Example here: http://jsfiddle.net/uanjLy1n/

Font color is not working on exported chart. Also \<br> breaks align of the exported chart.

**Comment by sebastianbochan** [comment]
Defaulty only some HTML tags are supported in highcharts exporting. Further informations: http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting

**Comment by Atte902** [comment]
So there is nothing you can do to fix \<br> tag?

**Comment by highslide-software** [comment]
First of all, instead of using `<font>` you should use a span with styles, which is picked up by our SVG renderer. The SVG renderer also picks up the break tag: http://jsfiddle.net/highcharts/uanjLy1n/1/.

Second, we have already for some time experimented with allowing HTML in the exported charts as discussed at #2473. I have added that experimental code now, which will be available from the next release. You enable it by setting `allowHTML` on the exporting config. [View it live on jsFiddle](http://jsfiddle.net/highcharts/uanjLy1n/2/).

**Comment by Atte902** [comment]
Thank you very much! I still have one problem. http://jsfiddle.net/uanjLy1n/3/ As you can see here, when autoRotation is set to false and it goes 2 line or more, exporting is not showing those lines, only three dots. Is there any way of fixin this, without seting rotation? With <br> tag, it is working correctly.

**Comment by highslide-software** [comment]
There's an option called `autoRotationLimit` that dictates when we allow word-wrapping of labels. The rationale is that when we get below a certain limit, we risk clipping words and wrapping doesn't work well. I know you disabled autoRotation, but is seems like the limit still applies. In your case, when viewing the chart on screen, it is probably wider than the 600 pixel used for export, so the output is different. You can fix that by setting a lower limit. [View it live on jsFiddle](http://jsfiddle.net/highcharts/uanjLy1n/4/).

**Comment by Atte902** [comment]
Again, thank you so much! But i have found new weird thing on that exporting. http://jsfiddle.net/uanjLy1n/5/

Now i have set useHTML to true on xAxis labels. But still that \<b> tag works. But when exported, those additional lines from labels are in left side of the image. Tags don't affect this, only setting useHTML to true causes it.
