### ISSUE TITLE
Bubble size and negative value

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4498]
In the example: http://jsfiddle.net/zth3r2yn/1/ marker with radius 5 for both points is not the same. I guess that we should be visualise as absolute radius.

Next example for analyse: http://jsfiddle.net/zth3r2yn/3/ marker with 5 and -100 looks like very similar (like 5 value), but have completle different values.

**Comment by sebastianbochan** [comment]
In case when we set null or 0 value, then bubble is printed. This is correct (because minSize is applied). When minSize is set for zero, then null/zero bubble is not printed. http://jsfiddle.net/zth3r2yn/7/ still correct. But when we use negative value, all seems to be fliped. http://jsfiddle.net/zth3r2yn/8/

**Comment by highslide-software** [comment]
I can't see anything wrong with the initial two demos - the point with the lowest value is printed smallest, and the largest point with the largest bubble. It doesn't matter that they are positive or negative, only the relative size matters. 

Would you expect that the bubbles were larger for larger absolute values, so that 0 is smallest and -100 and 100 are the same size? In that case we need to add logic.

**Comment by hmha** [comment]
Yes, having -100 & 100 of the same size sounds like a reasonable way of presenting on a bubble chart, because a chart probably will present values from the same context(for example gains and loses), thus the size of area should be the same.
Can you think of a business case where current logic does make sense ?

**Comment by highslide-software** [comment]
> Can you think of a business case where current logic does make sense ?

Haha, that's a good question! I can't, but on the other hand, no one can imagine all the different business cases I have met while working with Highcharts! What is a bug to one user, is a requirement to others.

PS - here's one: http://jsfiddle.net/highcharts/gLwbma4c/

**Comment by hmha** [comment]
That's impressive use case! :)
We would appreciate a switch for those two logics.

**Comment by highslide-software** [comment]
OP's demos with the fix applied: 
* http://jsfiddle.net/highcharts/zth3r2yn/11/
* http://jsfiddle.net/highcharts/zth3r2yn/12/
