### ISSUE TITLE
yAxis: {floor: 0} breaks highmaps

### ISSUE THREAD

**Issue by andrei-picus-hs** [highslide-software/highcharts.com#4561]
## Need

```gherkin
As a developer
I want Highmaps to ignore options that aren't available for it
So that I can send common options to all of my charts.
```

#### Use case:

I create my charts with `new Highcharts({chart: {type: <type>}})` and have a dict of common options applicable to all kinds of charts. I'd like to put `floor: 0` in that dict.

#### Demo

http://jsbin.com/geturi/edit?js,output

**Comment by highslide-software** [comment]
Thanks for the input, but axis options are available in Highmaps in order to control the zoomed area. You can also set min, max, minPadding, maxPadding etc. You should rather find another way of setting these options, for example based on the series type. Always setting `floor` to series will also break a lot of other cases, like any cartesian series with negative values for instance.
