### ISSUE TITLE
zAxis - not working with logarithmic type

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4562]
Example: http://jsfiddle.net/c10b0epg/2/

**Comment by pawelfus** [comment]
Two issues here:

- #4507 - kicks in
- when translating z-values, still default ones are used for plot position

**Comment by pawelfus** [comment]
*Internal note:*
I know that [this line](https://github.com/highslide-software/highcharts.com/commit/6ad1dd8bd770ef3dee1bb85a08d1dbeefcbc401f#diff-24a874c7610ddfbb26f6f2462112addcL1444) could be changed to `translate(z, 0, 0, 0, 1, 0)` to allow `translate()` calculate proper z-value, but since we needed this before (to determine if point is inside plotting area: [here](https://github.com/highslide-software/highcharts.com/commit/6ad1dd8bd770ef3dee1bb85a08d1dbeefcbc401f#diff-24a874c7610ddfbb26f6f2462112addcL1439)) then it is not necessary to calculate the same twice (first for `isInside` then in `translate`).

**Comment by highslide-software** [comment]
@pawelfus Maybe you can translate it once to a `plotZ` value, following the pattern of `plotX` and `plotY`?

**Comment by pawelfus** [comment]
Done
