### ISSUE TITLE
'webkitMovementX' is deprecated. Please use 'movementX' instead.

### ISSUE THREAD

**Issue by joostshao** [highslide-software/highcharts.com#4568]
'webkitMovementX' is deprecated. Please use 'movementX' instead.

'webkitMovementY' is deprecated. Please use 'movementY' instead.

/*
 Highcharts JS v3.0.10 (2014-03-10)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(){function s(a,b){var c;a||(a={});for(c in b)a[c]=b[c];r

chrome:  版本 45.0.2454.85 (64-bit)

**Comment by pawelfus** [comment]
It's thrown during extending (event probably). Demo: http://jsfiddle.net/wbjrzag6/2/ - click on some of the points and we will get warning. Probably soon it will be removed from Chrome and we don't get that warning. Otherwise we need to add extra conditions when extending **any** object:

    var extend = Highcharts.extend = function (a, b) {
	var n;
	if (!a) {
		a = {};
	}
	for (n in b) {
        if (n !== "webkitMovementX" && n !== "webkitMovementX") {
	   	    a[n] = b[n];
        }
	}
	return a;
    };

Or manually delete that properties before extending event.

**Comment by highslide-software** [comment]
Similar issues have appeared earlier and are fixed with [this code block in JQueryAdapter.js](https://github.com/highslide-software/highcharts.com/blob/v4.1.8/js/parts/JQueryAdapter.js#L253-L263):

```js
			// Remove warnings in Chrome when accessing returnValue (#2790), layerX and layerY. Although Highcharts
			// never uses these properties, Chrome includes them in the default click event and
			// raises the warning when they are copied over in the extend statement below.
			//
			// To avoid problems in IE (see #1010) where we cannot delete the properties and avoid
			// testing if they are there (warning in chrome) the only option is to test if running IE.
			if (!isIE && eventArguments) {
				delete eventArguments.layerX;
				delete eventArguments.layerY;
				delete eventArguments.returnValue;
			}
```

As Pawel says the warnings will eventually go away. But we could make those deprecated events a property on Highcharts or on the adapter so that they can be extended from the outside.

**Comment by joostshao** [comment]
thank you
