### ISSUE TITLE
Pie chart data label displays null values when format is set

### ISSUE THREAD

**Issue by dugokontov** [highslide-software/highcharts.com#4641]
As far as I know, pie chart is the only chart that displays data label for `null` value if data label's format is set.

Here is example that shows
 * pie chart: http://jsfiddle.net/h95qw79d/
 * column chart: http://jsfiddle.net/h95qw79d/1/

As you can see, on pie chart we see data label **%**, while on column chart nothing is shown.

Changing https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/DataLabels.js#L62 to

    enabled = pick(pointOptions && pointOptions.enabled, generalOptions.enabled) && point.y !== null; // #2282

fixed this issue, but I'm not comfortable with code to be sure it will not break something else.

Anyway, quick fix for this is to set `dataLabels.enabled = false` for all points where `y === null`.

**Comment by highslide-software** [comment]
For the records, the null point's data label is hidden on cartesian series because it is not inside the plot area as per the check at https://github.com/highslide-software/highcharts.com/blob/v4.1.9/js/parts/DataLabels.js#L175. This check is not performed on non-cartesian series, so I agree with your proposal of lifting the check to an earlier stage. I'll run 
tests and commit if everything is good.
