### ISSUE TITLE
TreeMap Back button is not visible

### ISSUE THREAD

**Issue by numerouno979** [highslide-software/highcharts.com#4663]
TreeMap Back button is not visible when you remove chart title and subTitle.
http://jsfiddle.net/gLp2LrxL/

**Comment by highslide-software** [comment]
@jon-a-nygaard The tree map back button should follow the same default placement and general structure and appearance as the drillUp button in the drilldown module.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting. This issue is solved in the next maintenance release. 
Those who would like to fix the issue before the next maintenance can do **one** of the following fixes:
- Download the latest version of treemap.src.js from this repository
- Use one of the quickfixes provided below.

### Quickfix 1
Open the treemap.src.js in an editor and go to line nr 82.
```javascript
// Replace this code snippet
drillUpButton: {
	position: { 
		align: 'left',
		x: 10,
		y: -50
	}
}
// with this code snippet below
drillUpButton: {
	position: { 
		align: 'right',
		x: -10,
		y: 10
	}
}
```

### Quickfix 2
In your chart options, set the following:
```javascript
var chart = new Highcharts.Chart({
    ...
    // Provide these options
    drillUpButton: {
		position: { 
			align: 'right',
			x: -10,
			y: 10
		}
    },
    ...
});
```
