### ISSUE TITLE
Drag selection around multiple points

### ISSUE THREAD

**Issue by arsinawaz** [highslide-software/highcharts.com#4682]
I want to implement multiple points selection in one go, i have found this help from the following links but i am not able to create the required behavior, can some help me and provide with a sample code..

http://forum.highcharts.com/highcharts-usage/drag-selection-around-multiple-points-t31553/#p110834

with the link below i am able to select multiple points but it fires multiple events for multiple points, i want to do it in one go and fire one event for one selection.
http://forum.highcharts.com/post33650.html?hilit=select%20multiple%20rectangle#p33650

Thanks in advance.

**Comment by highslide-software** [comment]
Hi,

I set up a proper, unit-tested demo at http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/events-selection-points/. 

How does this work for you? I added a custom event, `selectedpoints`, that you can use instead of single point events.

**Comment by arsinawaz** [comment]
Wow that is exactly what i wanted, thanks for quick reply and sample code.. :)

**Comment by highslide-software** [comment]
You're welcome!
