### ISSUE TITLE
All labels not displayed on a bar chart

### ISSUE THREAD

**Issue by tugdu** [highslide-software/highcharts.com#4708]
When creating a bar chart with few categories, series and values, all the labels containing the values are not displayed.
You can show that on official demo of basic bar (http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bar-basic/) -> label containing "107" for serie "1800" in Africa, label containing "31" in serie "1800" in category "America" and label containing "6" in serie "1900" in Category "Oceania" are not displayed.

**Comment by KacperMadej** [comment]
This is because of default label collision detection logic that hides labels that are too close to each other. This can be resolved through setting smaller padding (default is 5) or allowing overlapping for labels through `allowOverlap` option - API: http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.allowOverlap

This is not a bug. For support please check one of the support channels. More information: http://www.highcharts.com/support

**Comment by tugdu** [comment]
Thanks for the quick response. I'll check the given page next time before posting
